### ISSUE TITLE
Customers leaving after a certain while, based on their satisfaction

### ISSUE THREAD

**Issue by JanVeen** [LCfP/Serious-Game-for-Kids#79] opened 2016-12-15 14:50 UTC
See also #59 for the demand satisfaction part. In Dutch,

>Klanten moeten in principe ook weer kunnen weglopen als ze te lang hebben moeten wachten. Dit stond al op de originele planning voor v1.0, maar daar zijn we toen niet meer aan toegekomen (wij noemden het toen satisfaction). Dit moet wel heel grafisch kunnen worden uitgedrukt, met misschien een kort tekstje dat de klant produceert, en een kleur/emoticon die hun gemoedstoestand uitdrukt.

**Comment by N-Wouda** [comment] 2016-12-17 14:12
@JanVeen I believe this matches your point-deficit, so would you care to do this one? I understand this one may be quite difficult/abstract, and as such, perhaps you and @lukko could switch your assigned issues? 

Luc, you mainly have some 'smaller', more straightforward ones that I think may be easier to solve for Jan Willem. If you take on solely this one instead of those smaller ones, I think that would balance things out a bit better along skill levels, and not be too impossible for either of you guys.

**Comment by lukko** [comment] 2016-12-17 14:31
I understand your concerns, but the problem is that I really don't have the time these weeks to spent more hours than I should.

**Comment by N-Wouda** [comment] 2016-12-17 15:10
Very well. Then I'm assigning this to you @JanVeen.

**Comment by N-Wouda** [comment] 2016-12-17 15:14
>I understand your concerns, but the problem is that I really don't have the time these weeks to spent more hours than I should.

We assigned 23 points (69h), for only 56h of 'payment'. I hope you understand `1pt=3h` ought to be taken a bit more fluid than "I'm only going to do the bare minimum".

**Comment by N-Wouda** [comment] 2017-01-12 14:25
To be done at a later date. A smaller, similar issue will need to be done for Sprint 5.

**Comment by N-Wouda** [comment] 2017-08-09 16:15
Partially tackled this in #138.

**Comment by N-Wouda** [comment] 2017-09-25 09:09
While customers should be able to walk away, we may need to introduce a constraint on the number of customers at any given time,

>En constraint toevoegen dat bij 50 orders in de backlog geen nieuwe orders meer bij komen.

I don't think that constraint should be at 50 total, but lets make it into a parameter (default 20?).

**Closed as completed** 2018-03-18 18:51 UTC
Labels: enhancement
